### ISSUE TITLE
SIWE - showing the hex string instead of actual challenge

### ISSUE THREAD

**Issue by sasicodes** [block-wallet/extension#234]
Is this intended?

<img width="344" alt="image" src="https://user-images.githubusercontent.com/29498872/203964708-80407cca-ba30-4321-b6e8-2d1c601d726b.png">

btw the interface looks nice!

**Comment by julianariel** [comment]
hey @sasicodes!

Thanks a lot for your report and your compliment 😁 . 

Can you please give us a bit more context about the message you're trying to sign and what should be the expected output?

**Comment by sasicodes** [comment]
Currently, it's showing the hex string (may be encrypted?) but the message I intended to sign was the raw message.

<img width="298" alt="image" src="https://user-images.githubusercontent.com/29498872/204036609-ff275ba1-df43-439a-ba4f-788567f458f1.png">

**Comment by julianariel** [comment]
@sasicodes perfect, thanks for the clarification. We'll analyze this and come up with a solution soon.

**Comment by raster21** [comment]
I believe this is because you're currently not supporting [EIP-712](https://eips.ethereum.org/EIPS/eip-712).
Any plans to implement it soon?

**Comment by julianariel** [comment]
@raster21 EIP-712 is fully supported by BlockWallet, you can try this on any site that provides support for a typed message. 

In this case, the message you're trying to sign it's not typed, it's just a string that we're not converting properly before displaying it, will be fixed soon! I'll let you know.

**Comment by raster21** [comment]
@julianariel I was wrong! I had a second look and EIP-712 message signing works perfectly. However, I did face the same problem as the OP with hex strings not being properly decoded to ASCII.

**Comment by julianariel** [comment]
hey @sasicodes @raster21 , 

The fix for this issue was launched on BlockWallet's latest version, [v0.5.1](https://github.com/block-wallet/extension/releases/tag/v0.5.1).

Thanks for helping us make it better!
