### ISSUE TITLE
Performing an account reset

### ISSUE THREAD

**Issue by raster21** [block-wallet/extension#236]
It would be great to be able to perform an account reset. Here's the [documentation from Metamask](https://metamask.zendesk.com/hc/en-us/articles/360015488891-How-to-reset-an-account) talking about this feature. For example, this can be handy if a Flashbots RPC tx is dropped (not included) but is still showing up as pending in the wallet. It can also be helpful for developers doing dApp development locally.

Note: I am not referring to a general reset where you nuke all your accounts, but rather, the ability to reset the local TX state.

**Comment by julianariel** [comment]
hey @raster21 , thanks again for your input, this is valuable feedback.

We'll add this to our backlog to analyze it and ship it as soon as we can. 

Thanks!

**Comment by julianariel** [comment]
hey @raster21 ,

this feature was implemented in our latest version, you can access it through the current account menu > Reset Account.

Attached example video:

https://user-images.githubusercontent.com/11839151/210231201-69cdf7cc-0c2b-4f44-84cb-1dfb31026c9e.mov

Thanks!

**Comment by raster21** [comment]
Thanks @julianariel great to see this being deployed!
One question: why did the team choose to make the user unlock the wallet again after the account is reset?

**Comment by julianariel** [comment]
@raster21 because by locking and unlocking the wallet, we ensure that everything gets reloaded again and that the information from the chain gets reconstructed in a controlled way
