### ISSUE TITLE
Prompting doesn't work

### ISSUE THREAD

**Issue by AidenNguyen142** [block-wallet/extension#251]
Sometimes the network changing (and other activities as well -  I'm not 100% sure) prompt doesn't work, it just appears like the screenshot.

![image](https://user-images.githubusercontent.com/113259152/205568068-89da9913-a228-490e-b1b8-02007f091b6c.png)

I will have to click the extension to continue my work. 

**Desktop:**
 - OS: Windows 10
 - Chrome
 - Version 108.0.5359.95

**Comment by julianariel** [comment]
hey @AidenNguyen142 , thanks again for your valuable feedback!

This issue has been reported before so we were already working on a fix and improvements to the same process. I linked the Pull Request that contains those fixes, it will be included in our next release soon.

We'll keep you posted!

**Comment by julianariel** [comment]
hey @AidenNguyen142,

We've implemented a bunch of fixes and improvements for this issue on BlockWallet's latest version, [v0.5.1](https://github.com/block-wallet/extension/releases/tag/v0.5.1). Please check it out and feel free to submit any problem you find again.

Thanks for helping us make it better!
