### ISSUE TITLE
Sub-Accounts dissapearing

### ISSUE THREAD

**Issue by Budddog** [block-wallet/extension#257]
**Describe the bug**

Sub-Accounts Dissapear.

I have 12 accounts from the same seed. Every time the wallet restarts it only loads the 1st 5. the last 7 always dissapear from the wallet but are still there.

**To Reproduce**
Go to Wallet. Create 12 accounts. Log out. Close Chrome. See if they're still there when you re-open

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
MAC + CHrome (latest)

**Additional context**

**Comment by Budddog** [comment]
Hi Julian

Please see attached 2 screenshots.

The wallet app froze, gave a bug warning (didn't get time to screenshot it)
and it closed. After reopening only 5 accounts are there.

Please see 2 screenshots of before and after (12 vs 5 accounts).

This happens every time my Mac has been off for a while or if the wallet
freezes and resets itself

It always reverts back to those 5 accounts

Thanks
[image: Screenshot 2022-12-07 at 06.00.52.png][image: Screenshot 2022-12-07
at 06.03.29.png][image: Screenshot 2022-12-07 at 06.03.36.png]

**Comment by julianariel** [comment]
hey @Budddog , I'm sorry but the images you provided cannot be seen on GitHub, there are only file names: 

![image](https://user-images.githubusercontent.com/11839151/206535525-ac1f53fe-f9ec-48eb-8e5a-8fa0f698dd3d.png)


can you please re-send them? In addition, can you please access the extension page in Chrome at [chrome://extensions/](chrome://extensions/) and see if the **Errors** button is visible? In case it is, please open it and send us a screenshot of that content too.

![image](https://user-images.githubusercontent.com/11839151/206536723-f0986976-1464-4d71-b1f9-a6b9f5cd647b.png)


thanks!

**Comment by Budddog** [comment]
Hi Julian

Just thought i'd let you know.

I *was* having massive bugs / issues.

I didn't have an ERRORS button. HOWEVER, i did go into developer mode and i
'repacked' the program.

Now all the errors are gone and its working smoothly.

All the best

A
