### ISSUE TITLE
Can't seem to be able to activate the ''Flashbot Protection'' on any swaps within BlockWallet

### ISSUE THREAD

**Issue by LevelUpTrading** [block-wallet/extension#258]
**Describe the bug**

I tried to swap some of my WETH to PSP (Paraswap token), and wanted to activate the FlashBot Protection to make sure I am not getting front ran or something. 

I wasn't able to toggle the Protection on, and the reason why is because, I quote: 

''Transactions consuming less than 42,000 Gas will be mined normally, without Flashbots''

![image](https://user-images.githubusercontent.com/75787086/205995911-491f0f60-01ff-4971-a7d3-edb49e168530.png)
![image](https://user-images.githubusercontent.com/75787086/205996009-cc14b989-4927-4f40-926c-24e785e10458.png)

I then proceeded in trying to swap my WETH to another token, but yet again, I wasn't able to toggle it on, same reason.

**To Reproduce**
1. Go to 'BlockWallet, log into your wallet'
2. Click on 'Swap'
3. Choose WETH, and you are looking to Swap it for any token. let's take Paraswap's token as example 'PSP'
4. Click on ''Review''
5. Got and try to toggle ''FlashBot Protection'' to ''On''.
6. You will see you can't.

**Expected behavior**
I would expect that every single transaction I make through BlockWallet would give me the ability to protect myself against FlashBots.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser [Decentr - Chromium based Browser]
 - Version [Decentr 1.3.3 Based on Chromium 100.0.4896.80]

**Additional context**
Maybe you can only use FlashBot protection for certain swaps? I am not sure if I am doing something wrong, or if there is a bug with the flashbot protection within BlockWallet.

Thank you!

**Comment by julianariel** [comment]
Hey @LevelUpTrading , thanks for the very detailed report!

As you expect, you should be able to use Flashbots for this kind of swap transaction. We found an issue on that modal, and we'll be working on a fix soon.

We'll keep you updated,

Thanks!

**Comment by julianariel** [comment]
hey @LevelUpTrading  , 

The fix for this issue was launched on BlockWallet's latest version, [v0.5.1](https://github.com/block-wallet/extension/releases/tag/v0.5.1). Please feel free to try it again and informing us of any problems.

Thanks for helping us make it better!
