### ISSUE TITLE
Issue with ETHW-mainnet network 

### ISSUE THREAD

**Issue by Parkerclub** [block-wallet/extension#274]
![image](https://user-images.githubusercontent.com/66799400/207166541-4de22e2c-010c-4159-b2bc-ff5d5d4f5245.jpg)

Hanging screen of the wallet when switching to ETHW-mainnet!

1. Add ETHW-mainnet
2. Click on it
3. See error

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [brave ,i]

After updating to the latest version I found out this problem with ETHW-mainnet network! I’ve tried to switch to ETHW network, the wallet started to load and kept hanging all the time so I wasn’t able to use wallet even switch to other networks!I had to delete it from extension and do recovery procedure!

**Comment by julianariel** [comment]
hey @Parkerclub, thanks for your submission

We're working on fixing this problem and will update you soon. Sorry for the inconvenience.

Thanks!

**Comment by Parkerclub** [comment]
Thank you for cooperation)

**Comment by julianariel** [comment]
hey @Parkerclub, 

This issue was fixed with our latest update. BlockWallet version 0.5.2 should work ok now; please restart your browser and try again.

Sorry for the inconvenience and thanks for your patience.

**Comment by Parkerclub** [comment]
Thanks a lot! It works perfect 🙏
