### ISSUE TITLE
Bridged Ether from Ethereum to Arbitrum, but stuck on pending.

### ISSUE THREAD

**Issue by agb84** [block-wallet/extension#276]
**Is your feature request related to a problem? Please describe.**

Hash: 0x2f0ec9a5905ef2df9a2df5b8f4e9a7ffe5696c3c58ace576c181e7dd2ac72276

Bridged 0.69 Ether to Arbitrum.  The ethereum hash shows "successful" status, but nothing came through on the Arbitrum side, and it is still showing as pending in Block Wallet.

**Describe the solution you'd like**
To have the funds arrive in my block wallet on arbitrum as intended when bridging.

**Describe alternatives you've considered**
Not sure... I have sufficient funds in ether on both ethereum and arbitrum to cover gas.

**Additional context**
Spoke to Dylan on Telegram today (Block Wallet admin on Dec 12, 2022 from 8-9pm Eastern) who recommended I post here to get this resolved.  

Thank you so much for your help.  This is a lot of money to me!

<img width="350" alt="image" src="https://user-images.githubusercontent.com/66561261/207207495-73676ef9-8a27-435b-9bd3-fdca05597bf9.png">

**Comment by julianariel** [comment]
hey @agb84, thanks for your report.

Is this bridge still pending? Can you please switch to Ethereum Mainnet, click on the bridge, and share a screenshot of the details?

Thanks!

**Comment by agb84** [comment]
Hi Julián,

Yes, the bridge is still pending. :(
Screenshots below.  Has shown “< 6 minutes" for like 12 hours now. 

￼￼￼

**Comment by julianariel** [comment]
hey @agb84,

Unfortunately, we cannot see the provided images; it seems there was a problem with the attachment. Can you please share them again? Or please check the **tool** field in the same modal and let us know what it says so we can check what's going on.

Thanks!

**Comment by agb84** [comment]
<img width="920" alt="Screenshot 2022-12-13 at 9 29 37 AM" src="https://user-images.githubusercontent.com/66561261/207360363-3c5bd818-f69e-4507-be30-81761671d072.png">

**Comment by julianariel** [comment]
@agb84 thanks for the screenshots!

It seems that the bridge is finally completed now. We reported the situation to our bridges provider so they could better inform us about what happened.

Please try restarting the browser or reloading the extension to get the bridge updated, and let us know if it's ok.

**Comment by agb84** [comment]
Amazing, Thank you :)
Block Wallet is the Best!  
Also loving the updates..

Best,
Adam
