### ISSUE TITLE
Can't seem to connect my BlockWallet to a lot of different Crypto related websites/dApps

### ISSUE THREAD

**Issue by LevelUpTrading** [block-wallet/extension#278]
**Describe the bug**
Can't seem to connect my BlockWallet to a lot of different Crypto related websites/dApps

**To Reproduce**
1. Go to https://buffer.finance/ or https://staking.chain.link/
2. Click on 'Connect Wallet'
3. You can try and click on the MetaMask logo, but you will see a error pop up saying you need to install that wallet. The interaction with the MetaMask logo does not open up BlockWallet.

These are just 2 Crypto related websites or dApps that face this issue, there are many out there that won't recognize BlockWallet unfortunately.

**Expected behavior**
You would expect every Crypto related website or dApp have the ''Inject'' option when it comes to connecting with a Web3 wallet, unfortunately, many of them don't have the ''Inject'' option. They do offer the MetaMask option, which should open up the BlockWallet pop up, but in many cases, nothing happens, unfortunately.

**Screenshots**
Some screenshots:

(Here the platform shows an error because I don't have MetaMask installed, I only use BlockWallet).

![image](https://user-images.githubusercontent.com/75787086/207390337-56c3f229-ec76-4c7e-b64e-e4fc160c59e9.png)

(Here, the Chainlink staking platform doesn't let me connect my BlockWallet by clicking on the MetaMask logo, actually, the only thing that happens in that, where it used to say ''connect wallet'' it now says ''install wallet''.

![image](https://user-images.githubusercontent.com/75787086/207390447-c29ba929-f227-4381-88e5-7e4d63810dae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Ungoogled Chormium
 - Version Version 108.0.5359.95

**Additional context**

Thank you for the hard work, making BlockWallet better each single update.
Keep it up!

**Comment by LevelUpTrading** [comment]
Amazing that you added a new repository from where we can add new sites to that list and make them work without having to release a new version of the wallet. I just tried to connect my BlockWallet to that Chainlink staking page, but nothing happens unfortunately. I tried the BufferFinance page also, but no success, still gives me the same error! Not sure why tho, as you mentioned, it should work now.

Thank you for the hardwork! You are awesome!

**Comment by julianariel** [comment]
hey @LevelUpTrading ,

thanks for your kind words, we really appreciate them 💪🏻 

Regarding the sites not working, let's try a few things:
- Did you restart the browser after trying again?
- Do you have BlockWallet set as the default wallet? Find out how to check it on [this article](https://help.blockwallet.io/hc/en-us/articles/4672446037905-Setting-BlockWallet-as-your-Default-Browser-Wallet)
- Can you please check which BlockWallet version are you running? can be seen at the end of settings page
![image](https://user-images.githubusercontent.com/11839151/207640383-80c9379a-cb3a-410d-b220-9fa7e0877e49.png)

Let me know what you find,

Thanks!

**Comment by LevelUpTrading** [comment]
So I disabled the BlockWallet extension in my browser, enabled it again after, logged in and went to the Chainlink staking website and guess what? I can now connect my BlockWallet by pressing the MetaMask logo! The other website also worked! Great to see this fixed!

Just tobe sure, I will send you the details you asked for:

Did you restart the browser after trying again?
No, but when I did, it all worked!

Do you have BlockWallet set as the default wallet? Find out how to check it on [this article]
Yes I do have it as default wallet! MetaMask was never installed on this browser!

Can you please check which BlockWallet version are you running? can be seen at the end of settings page
I am running BlockWallet version v0.5.1


Is there an easier way to add website that don't work when trying to connect BlockWallet, or do we need to file a bug report like I just did every single time I find a website that doesn't let me connect? 

Thank you again for the help!

**Comment by julianariel** [comment]
That's good to hear; I'm glad it worked!

Regarding your last question, instead of filing a bug report here, you can check out this [README ]( https://github.com/block-wallet/remote-configs/blob/main/provider/Readme.md) with instructions about how to add those sites to the list and submit a PR so we can push it forward quickly.

Let us know if you have any other problems; we're marking this issue as completed.

Thanks!

**Comment by LevelUpTrading** [comment]
Perfect! Thank you for sharing this with me.
Question tho, why not simply go to https://dappradar.com/rankings and add all the dApps that have some kind of a reputation for being legit to that list, so that BlockWallet would be working on most dApps! (Not sure if you already did this, I guess you guys did, but you never know!)
