### ISSUE TITLE
Question for JulianAriel

### ISSUE THREAD

**Issue by LevelUpTrading** [block-wallet/extension#290]
Hi Julian!

Thanks again for all your help lately.
You told me that I could go and read a ''read me'' and send a Pull Request. 
Unfortunately, I am not that common with Github, so I posted this, hopefully this is what you meant? 

![image](https://user-images.githubusercontent.com/75787086/207941764-c03746fa-6c80-4309-8383-ffba01d3ab09.png)

Thank you!

**Comment by julianariel** [comment]
Hey @LevelUpTrading , thanks for your contribution!

I see now that you managed to create the PR so I'll close this one.
