### ISSUE TITLE
Can't seem to be able to connect my BlockWallet to Uniswap by clicking on the MetaMask logo

### ISSUE THREAD

**Issue by LevelUpTrading** [block-wallet/extension#291]
**Describe the bug**
Can't seem to be able to connect my BlockWallet to Uniswap by clicking on the MetaMask logo.

**To Reproduce**
1. Go to https://app.uniswap.org/#/
2. Click on 'connect'
3. See error

**Expected behavior**
You would expect it to connect to such a popular DEX.

**Screenshots**
![image](https://user-images.githubusercontent.com/75787086/207980586-8185d77e-aeb9-4311-8aec-f95fa80f04b9.png)

Thank you!

**Comment by LevelUpTrading** [comment]
I just checked if BlockWallet is set as default wallet on my chrome, and it is.
I then restarted my Chrome and went to https://app.uniswap.org/, clicked on ''connect'' and this error pops up for me, just like yesterday.

![image](https://user-images.githubusercontent.com/75787086/208119998-e79d0f6b-7b0d-481b-8638-412c01d8dfeb.png)

There are a lot of websites that won't allow me to connect my Blockwallet it seems like.
Remember the Chainlink website I asked to be added so that I can connect my BlockWallet to? Doesn't work anymore..

![image](https://user-images.githubusercontent.com/75787086/208120278-edcb0f73-bd11-495f-9c30-132470729881.png)


Same goes for 1inch ( https://app.1inch.io/#/1/unified/swap/ETH/DAI ), I click on connect, select the ETH network, then click on the Metamask logo and nothing happens..

![image](https://user-images.githubusercontent.com/75787086/208120540-61da6932-68cb-4eee-86ba-be8efbfce76e.png)

The gTrade DEX  ( https://gains.trade/ ) used to work for me, but now, when I try to connect, again, nothing happens..

![image](https://user-images.githubusercontent.com/75787086/208120706-1d7ee5f3-34f4-46a8-bc29-b8a4ef2f4fab.png)

I think there is some bug somewhere, not sure what happened, it used to all work fine for me.

I hope you guys can find the bug and fix it! Thank you!

**Comment by julianariel** [comment]
It seems that there's an issue with your BlockWallet instance. Can you please:

- go to [chrome://extensions/](chrome://extensions/) , disable/enable BlockWallet, refresh the dApp page and try again
- if the issue persists, please enable developer mode and see if an Error button appears. Then please share a screenshot of its content
- do you have any other Wallets installed?
![chrome_jDXgj9JhaW](https://user-images.githubusercontent.com/11839151/208123710-c7726254-ff77-4131-8476-e429267a2f77.gif)

**Comment by LevelUpTrading** [comment]
I went to chrome://extensions/, I disabled, enabled BlockWallet extension, refreshed the Uniswap dApp, but still can't connect. It gives the same error as posted before.

I then enabled developer mode, and no ''Error'' button appears next to my BlockWallet extension.
![image](https://user-images.githubusercontent.com/75787086/208124893-214a0a29-f2a0-4dc4-a999-8d8c9175a4fa.png)


No I do not have any other Wallet extension on my browser, I am a full time BlockWallet user haha!

**Comment by julianariel** [comment]
thanks for your cooperation! 

ok then, can you please click on the **background page** link and keep this window open (on the **Console** tab) while you attempt to connect again, so we can see what is happening at the time of connecting?
![image](https://user-images.githubusercontent.com/11839151/208125840-f85c3999-4c7a-4a73-9e41-4d9c2eb7b9f1.png)

**Comment by julianariel** [comment]
don't worry about the version number, I'm working in a local environment with the next update that will be rolling out to everyone soon, but it's unrelated to this.

It seems something cached in your browser is breaking the dApps connection. Please try refreshing them one more time but pressing **Ctrl+F5** to ensure everything gets loaded again.

We don't have any other issue report related to this, Uniswap is working ok for everyone, and you're not receiving any errors so it's most likely an issue related to the browser.

**Comment by LevelUpTrading** [comment]
I disabled, re-enabled BlockWallet extension, went to the uniswap dApp, pressed Ctrl+F5, page reloaded fine, clicked ''connect'', then pressed the MetaMask logo, and still, the same error for some reason..

![image](https://user-images.githubusercontent.com/75787086/208130181-5a5a8a6c-7072-4f56-8830-17057db81996.png)


Any advice? Should I clear the cache of my browser and retry? I wish I didn't have to do that because all my stuff will be reset but if that's the only way to fix this issue..

Thank you!

**Comment by julianariel** [comment]
MetaMask button shouldn't appear at all in Uniswap with only BlockWallet installed, it should say "Browser Wallet". 

One more thing you can try before clearing the browser's cache is to reinstall BlockWallet and import your seed again. Let me know if one of these works 🙏🏻

**Comment by LevelUpTrading** [comment]
Just uninstalled the BlockWallet extension, re-downloaded it, imported my seed again. Opened up Uniswap, and the MetaMask logo is still showing when trying to connect, and when pressing on the MetaMask logo, I still get the same error.. I am so confused!

**Comment by LevelUpTrading** [comment]
I am using the latest version of Ungoogled Chromium, running it on Windows 10 Pro! I have been using Ungoogled Chromium for a longtime, everything was working fine until yesterday or the day before that, out of nowhere, I wasn't able to connect to any dApp using BlockWallet.

I will reboot the pc, and clear the cache of my browser if I don't find a fix! Can you keep this thread open, I will come back to you guys if I found a fix!

**Comment by LevelUpTrading** [comment]
So I just cleared the cache on my browser, yet, I still can't connect to any of the sites talked about above.
I am so confused.

I really don't know what to do actually haha..

**Comment by LevelUpTrading** [comment]
FIXED IT!

So what did I do?

Cleared ALL data from my browser.
Completely uninstalled ALL extensions I had.
Completely uninstalled Ungoogled Chromium.

Rebooted PC
Re-installed Ungoogled Chromium.
Re-installed all my extensions such as BlockWallet.
Import seed phrase.
Went to Uniswap, Paraswap, gTrade etc, they all let me connect to my BlockWallet now!

Funny, still don't understand what went wrong, what I do know, is that in the extension console, there is more info showing up than before when it did not work.

![image](https://user-images.githubusercontent.com/75787086/208166069-91adbbd5-8831-4891-93c0-6e51c2ce7508.png)

Seems like it's ''warning'', is this anything I need to be worried about?

Thank you again guys for trying to help me out! I am happy I can now use BlockWallet again :D

Have a great weekend!

**Comment by julianariel** [comment]
That's great news! 👏🏻  We've also added some of the dApps you reported that weren't working, like **Polygon Wallet**, **ThorWallet** and **ThorSwap**

Don't worry about that warning, it is no big deal, and it shouldn't affect the wallet functionality.

Thanks for your patience and hope you have a great weekend too!
