### ISSUE TITLE
Blockwallet is unresposive.

### ISSUE THREAD

**Issue by hendo5000** [block-wallet/extension#294]
**Describe the bug**
I am logged into BW with my password. I am trying to change from Arbitrum to Ethereum, but the dropdown to change networks is not responding. I have tried disabling the extension, and re-enabling it. Restarted the browser. Restarted the computer. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 22621.963
 - Browser Brave
 - Version 1.46.144 (Chromium 108.0.5359.128 (Official Build) (64-Bit)

**Additional context**
![2022-12-15 22_20_34-](https://user-images.githubusercontent.com/48262856/208015577-2a3cb074-0177-4c4c-8bdd-552dbbc3f35c.png)

**Comment by julianariel** [comment]
hey @hendo5000 , thanks for your submission!

This issue was fixed with our latest update. BlockWallet version 0.5.2 should work ok now; please restart your browser and try again. 

Sorry for the inconvenience,

Thanks!
