### ISSUE TITLE
Transaction fee's on the Polygon network within BlockWallet are not showing the USD value.

### ISSUE THREAD

**Issue by LevelUpTrading** [block-wallet/extension#299]
**Describe the bug**
There seems to be a bug within the gas fee tracker on the Polygon Network within BlockWallet.
The Ehereum Gas Fee tracker works fine, shows the current USD value of the fees, but not on the polygon network.

**To Reproduce**

- Go to BlockWallet and connect to the Polygon Network. Then click on the Gas Tracker logo, and it will not show the USD value of the gas fee.

**Expected behavior**
I would expect the Gas Tracker on the Polygon Network to work just as the Ethereum gas tracker works.

**Screenshots**

Ethereum Network Fee's showing USD value:
![image](https://user-images.githubusercontent.com/75787086/208122098-6fcab30e-8bf5-4c3f-b9e9-4ccd9b3ede9c.png)

Polygon Network Fee's not showing USD value:
![image](https://user-images.githubusercontent.com/75787086/208121995-2863ea34-036e-45a8-8770-5ddd8dc15ce1.png)

Fantom Opera network Gas price tracker is not showing any USD value either:
![image](https://user-images.githubusercontent.com/75787086/208122823-405f37cc-d3e7-4c83-85b5-f642746a873c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Ungoogled Chromium 
 - Version Version 108.0.5359.95 (Official Build, ungoogled-chromium) (64-bit)

Just wanted to make sure you guys were aware of this Gas price tracker bug on the Polygon and Fantom Opera networks within BlockWallet!

Thank you for the hard work, and sorry bombarding you with little bugs I find, I do think it is important to share them with you simply because we all want the same thing, a bug free experience for every BlockWallet user!

**Comment by julianariel** [comment]
hey @LevelUpTrading, 

Thanks a lot for your reports, they're all welcome and helpful to us so don't worry!

This specific one it's not a bug; gas prices for those networks are very low. Polygon sometimes gets a bit more expensive, but the point of this kind of network is to keep fees low. 

In our gas tracker, we calculate the cost for a basic send transaction. Same estimation you can find when trying to send funds:
![image](https://user-images.githubusercontent.com/11839151/208137019-a394e9a1-5905-4dea-a956-8a117335d5b8.png)
![image](https://user-images.githubusercontent.com/11839151/208137887-aa393bb5-3834-4061-a0e3-21b1c2269420.png)

USD value is so low that it is very close to zero.

Hope this clarifies it,
