### ISSUE TITLE
Change "per gas" to "per gas unit" to improve UX

### ISSUE THREAD

**Issue by mbitto** [block-wallet/extension#302]
**Describe the bug**
In some phases of the extension's UX labels are inconsistent 

**To Reproduce**
1. Create a transaction
2. Open the “Gas Price“ window within the “Confirm” transaction window 
3. See Max Tip (per gas) and Max fee (per gas).
4. It would be clearer if labels text includes  “Per gas unit”

**Additional context**
I'd also take the chance to cleanup uppercase / lowecase inconsistencies

**Comment by julianariel** [comment]
hey @mbitto , thanks a lot for your contribution!

We've reviewed your requested changes, and they seem ok. We will include them in our next version.

Regards,
