### ISSUE TITLE
Cannot approve tokens on Arbitrum

### ISSUE THREAD

**Issue by PlaybackProdigy** [block-wallet/extension#312]
**Describe the bug**
I've been using the wallet for a few weeks with great results until suddenly tonight I am unable to approve tokens on Arbitrum. I'm interacting with Balancer and Uniswap and in both cases new tokens (including WETH) will not approve, but previously-approved tokens swap and behave normally. I tried restarting the browser, computer and extension and it still is happening.

The error message reads:  
Transaction failed: Cannot read properties of undefined (reading 'code')

**To Reproduce**
1. Go to Balancer
2. Click on Approve Tokem 
3. See error

**Expected behavior**
Expected to approve and swap/use the tokens normally

**Screenshots**
![Screenshot 2022-12-22 6 42 10 PM](https://user-images.githubusercontent.com/68773155/209280961-2b81a38f-7889-41d2-9ee1-99ea02fe89f5.png)

**Desktop (please complete the following information):**

 - OS: Chromebook
 - Browser Chrome
 -  Version 107.0.5304.110 (Official Build) (64-bit)

**Additional context**
Very strange and frustrating behavior, please help I need to make moves!

**Comment by julianariel** [comment]
hey @PlaybackProdigy , thanks for your submission!

This issue was fixed with the latest BlockWallet v0.5.4 update. Can you please try the operation again?

Sorry for the inconvenience,

Regards,
