### ISSUE TITLE
Ivalid big number Issue

### ISSUE THREAD

**Issue by romanornr** [block-wallet/extension#337]
**Describe the bug**

**To Reproduce**
Visit: https://app.collectif.finance/
Add: https://chainlist.org/chain/3141
Testnet filecoins: https://hyperspace.yoga/#faucet (put in address)
Stake 5 FIL for clFIL

Then the error happens 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Kernel: x86_64 Linux 6.1.6-arch1-3
- Blockwallet: v5.0.4
 - Browser: Version 110.0.5481.38 (Official Build) beta (64-bit)

**Additional context**
I downloaded the statelogs which I can sent via telegram privately 

![Screenshot from 2023-01-27 16-00-18](https://user-images.githubusercontent.com/6548898/215117733-050bf495-64b8-4a52-87f3-0705f778a7ea.png)

**Comment by julianariel** [comment]
hey @romanornr , thanks for your detailed submission.

We found the problem causing this issue, and we've applied a fix that will roll out in our next update. We'll keep you posted here.

Thanks!

**Comment by julianariel** [comment]
@romanornr the fix for this issue is now available on the latest BlockWallet version, please try the operation again and let us know if you encounter any problems.
